export const STRINGS = {
  en: {
    settingsTitle: "Settings",
    settingsSubtitle: "Configure how GitAnimals behaves on your desktop.",
    sidebarGeneral: "General",
    sidebarAgents: "Agents",
    sidebarTheme: "Theme",
    sidebarAbout: "About",
    sidebarSoon: "Soon",
    aboutSubtitle: "App version and links.",
    aboutVersion: "Version",
    aboutLicense: "License",
    aboutLicenseValue: "MIT",
    aboutRepository: "Repository",
    aboutHomepage: "Homepage",
    aboutOpenLink: "Open",
    sectionAppearance: "Appearance",
    sectionStartup: "Startup",
    sectionBubbles: "Bubbles",
    agentsTitle: "Agents",
    agentsSubtitle:
      "Turn tracking on or off per agent. Disabled agents stop log monitors and drop hook events at the HTTP boundary — they won't drive the pet, show permission bubbles, or keep sessions.",
    agentsEmpty: "No agents registered.",
    eventSourceHook: "Hook",
    eventSourceLogPoll: "Log poll",
    eventSourcePlugin: "Plugin",
    badgePermissionBubble: "Permission bubble",
    rowAgentPermissions: "Show pop-up bubbles",
    rowAgentPermissionsDesc:
      "Turn off to let this agent handle prompts in its own terminal instead of showing a permission bubble.",
    rowLanguage: "Language",
    rowLanguageDesc: "Interface language for menus and bubbles.",
    rowSound: "Sound effects",
    rowSoundDesc:
      "Play a chime when GitAnimals finishes a task or asks for input.",
    rowFlip: "Flip horizontally",
    rowFlipDesc: "Mirror the pet so it faces the other direction.",
    rowOpenAtLogin: "Open at login",
    rowOpenAtLoginDesc: "Start GitAnimals automatically when you log in.",
    rowStartWithClaude: "Start with Claude Code",
    rowStartWithClaudeDesc:
      "Auto-launch GitAnimals whenever a Claude Code session starts.",
    rowAutoCheckUpdates: "Automatically check for updates",
    rowAutoCheckUpdatesDesc:
      "Check for new versions in the background every 12 hours.",
    sectionUpdates: "Updates",
    updateCurrentVersion: "Current version",
    updateLatestVersion: "Latest version",
    updateLastChecked: "Last checked",
    updateNeverChecked: "Never",
    updateStatusIdle: "Ready to check for updates.",
    updateStatusChecking: "Checking GitHub for the latest release…",
    updateStatusAvailable: "A newer version is available.",
    updateStatusDownloading: "Downloading the update now…",
    updateStatusReady: "The update has been downloaded and is ready to install.",
    updateStatusError: "The last update attempt failed.",
    updateStatusUpToDate: "You're on the latest version.",
    updateCheckNow: "Check now",
    updateDownloadNow: "Download update",
    updateInstallNow: "Install update",
    updateRestartNow: "Restart to update",
    updateFlowGit: "Development checkout",
    updateFlowAuto: "Packaged app",
    rowBubbleFollow: "Bubbles follow the pet",
    rowBubbleFollowDesc:
      "Place permission and update bubbles next to the pet instead of the screen corner.",
    rowHideBubbles: "Hide all bubbles",
    rowHideBubblesDesc:
      "Suppress permission, notification, and update bubbles entirely.",
    rowShowSessionId: "Show session ID",
    rowShowSessionIdDesc:
      "Append the short session ID to bubble headers and the Sessions menu.",
    sectionMacOS: "macOS",
    rowShowInMenuBar: "Show in Menu Bar",
    rowShowInMenuBarDesc: "Display the GitAnimals icon in the macOS menu bar.",
    rowShowInDock: "Show in Dock",
    rowShowInDockDesc:
      "Display GitAnimals in the macOS Dock. At least one must stay visible.",
    sectionPrivacy: "Privacy",
    rowSendDiagnostics: "Send anonymous diagnostics",
    rowSendDiagnosticsDesc:
      "Share crash reports and anonymised event breadcrumbs so the maintainers can diagnose issues like the pet disappearing. No personal data.",
    placeholderTitle: "Coming soon",
    placeholderDesc:
      "This panel will land in a future GitAnimals release. The plan lives in docs/plan-settings-panel.md.",
    toastSaveFailed: "Couldn't save: ",
    langEnglish: "English",
    langChinese: "中文",
    themeTabTitle: "Theme",
    themeTabSubtitle:
      "Pinned themes appear in the right-click Persona submenu. At least one must stay pinned.",
    themeRefresh: "Refresh",
    themeRefreshing: "Refreshing…",
    themeRefreshDone: "Themes refreshed.",
    themeRefreshFailed: "Refresh failed: ",
    toastActiveLocked: "Cannot unpin the active theme.",
    toastMinOneRequired: "At least one theme must remain pinned.",
    toastPersonaRequired: "Get this pet at GitAnimals!",
    toastPersonaLink: "https://gitanimals.org",
    personaInfo: "Locked themes require a GitAnimals pet.",
    personaInfoLink: "Get one at gitanimals.org",
    langKorean: "한국어",
    userCardSignedIn: "Signed in",
    userCardLoading: "Loading account…",
    userCardSignOut: "Sign out",
    userCardSignInAgain: "Sign in again",
    sessionExpiredToast: "Session expired — please sign in again.",
  },
  zh: {
    settingsTitle: "设置",
    settingsSubtitle: "配置 GitAnimals 在桌面上的行为。",
    sidebarGeneral: "通用",
    sidebarAgents: "Agent 管理",
    sidebarTheme: "主题",
    sidebarAbout: "关于",
    sidebarSoon: "待推出",
    aboutSubtitle: "应用版本与相关链接。",
    aboutVersion: "版本",
    aboutLicense: "许可证",
    aboutLicenseValue: "MIT",
    aboutRepository: "代码仓库",
    aboutHomepage: "主页",
    aboutOpenLink: "打开",
    sectionAppearance: "外观",
    sectionStartup: "启动",
    sectionBubbles: "气泡",
    agentsTitle: "Agent 管理",
    agentsSubtitle:
      "按 agent 类型开关追踪。关闭后会停掉日志监视器、在 HTTP 入口丢弃 hook 事件——不会再驱动桌宠、不弹权限气泡、不记会话。",
    agentsEmpty: "没有已注册的 agent。",
    eventSourceHook: "Hook",
    eventSourceLogPoll: "日志轮询",
    eventSourcePlugin: "插件",
    badgePermissionBubble: "权限气泡",
    rowAgentPermissions: "显示弹窗",
    rowAgentPermissionsDesc:
      "关闭后让该 agent 在自己的终端里处理提示，不再弹 权限气泡。",
    rowLanguage: "语言",
    rowLanguageDesc: "菜单和气泡的界面语言。",
    rowSound: "音效",
    rowSoundDesc: "GitAnimals 完成任务或需要输入时播放提示音。",
    rowFlip: "水平翻转",
    rowFlipDesc: "镜像宠物使其面向另一方向。",
    rowOpenAtLogin: "开机自启",
    rowOpenAtLoginDesc: "登录系统时自动启动 GitAnimals。",
    rowStartWithClaude: "随 Claude Code 启动",
    rowStartWithClaudeDesc: "Claude Code 会话开始时自动拉起 GitAnimals。",
    rowAutoCheckUpdates: "自动检查更新",
    rowAutoCheckUpdatesDesc: "每 12 小时在后台检查新版本。",
    sectionUpdates: "更新",
    updateCurrentVersion: "当前版本",
    updateLatestVersion: "最新版本",
    updateLastChecked: "上次检查",
    updateNeverChecked: "从未",
    updateStatusIdle: "可以检查更新。",
    updateStatusChecking: "正在从 GitHub 检查最新发布版本…",
    updateStatusAvailable: "发现了新版本。",
    updateStatusDownloading: "正在下载更新…",
    updateStatusReady: "更新已下载完成，可以安装。",
    updateStatusError: "上次更新失败。",
    updateStatusUpToDate: "当前已是最新版本。",
    updateCheckNow: "立即检查",
    updateDownloadNow: "下载更新",
    updateInstallNow: "安装更新",
    updateRestartNow: "重启并更新",
    updateFlowGit: "开发仓库",
    updateFlowAuto: "已打包应用",
    rowBubbleFollow: "气泡跟随桌宠",
    rowBubbleFollowDesc: "把权限气泡和更新气泡放在桌宠旁边，而不是屏幕角落。",
    rowHideBubbles: "隐藏所有气泡",
    rowHideBubblesDesc: "完全屏蔽权限、通知和更新气泡。",
    rowShowSessionId: "显示会话 ID",
    rowShowSessionIdDesc: "在气泡标题和会话菜单后追加短会话 ID。",
    sectionMacOS: "macOS",
    rowShowInMenuBar: "在菜单栏中显示",
    rowShowInMenuBarDesc: "在 macOS 菜单栏中显示 GitAnimals 图标。",
    rowShowInDock: "在 Dock 中显示",
    rowShowInDockDesc:
      "在 macOS Dock 中显示 GitAnimals。菜单栏和 Dock 至少保留一个。",
    sectionPrivacy: "隐私",
    rowSendDiagnostics: "发送匿名诊断数据",
    rowSendDiagnosticsDesc:
      "共享崩溃报告和匿名化事件面包屑，帮助维护者诊断诸如桌宠消失之类的问题。不包含任何个人信息。",
    placeholderTitle: "即将推出",
    placeholderDesc:
      "此面板将在 GitAnimals 后续版本中加入，规划见 docs/plan-settings-panel.md。",
    toastSaveFailed: "保存失败：",
    langEnglish: "English",
    langChinese: "中文",
    themeTabTitle: "主题",
    themeTabSubtitle:
      "已固定的主题会出现在右键菜单的「角色」子菜单中。至少保留一个固定主题。",
    themeRefresh: "刷新",
    themeRefreshing: "刷新中…",
    themeRefreshDone: "主题已刷新。",
    themeRefreshFailed: "刷新失败：",
    toastActiveLocked: "无法取消固定当前使用的主题。",
    toastMinOneRequired: "至少需要保留一个固定主题。",
    toastPersonaRequired: "在 GitAnimals 获取这个宠物吧！",
    toastPersonaLink: "https://gitanimals.org",
    personaInfo: "锁定的主题需要 GitAnimals 宠物。",
    personaInfoLink: "前往 gitanimals.org 获取",
    langKorean: "한국어",
    userCardSignedIn: "已登录",
    userCardLoading: "加载账号…",
    userCardSignOut: "退出登录",
    userCardSignInAgain: "重新登录",
    sessionExpiredToast: "会话已过期 — 请重新登录。",
  },
  ko: {
    settingsTitle: "설정",
    settingsSubtitle: "GitAnimals의 데스크톱 동작 방식을 설정합니다.",
    sidebarGeneral: "일반",
    sidebarAgents: "Agents",
    sidebarTheme: "테마",
    sidebarAbout: "정보",
    sidebarSoon: "준비 중",
    aboutSubtitle: "앱 버전과 관련 링크예요.",
    aboutVersion: "버전",
    aboutLicense: "라이선스",
    aboutLicenseValue: "MIT",
    aboutRepository: "저장소",
    aboutHomepage: "홈페이지",
    aboutOpenLink: "열기",
    sectionAppearance: "모양",
    sectionStartup: "시작",
    sectionBubbles: "버블",
    agentsTitle: "Agents",
    agentsSubtitle:
      "Agent별로 추적을 켜거나 끌 수 있어요. 비활성화된 agent는 로그 모니터가 멈추고 HTTP 경계에서 hook 이벤트가 드롭돼요 — 펫을 움직이지도, 권한 버블을 표시하지도, 세션을 유지하지도 않아요.",
    agentsEmpty: "등록된 agent가 없어요.",
    eventSourceHook: "Hook",
    eventSourceLogPoll: "로그 폴링",
    eventSourcePlugin: "플러그인",
    badgePermissionBubble: "권한 버블",
    rowAgentPermissions: "팝업 버블 표시",
    rowAgentPermissionsDesc:
      "끄면 이 agent가 자기 터미널에서 프롬프트를 처리하고 권한 버블을 띄우지 않아요.",
    rowLanguage: "언어",
    rowLanguageDesc: "메뉴와 버블의 인터페이스 언어예요.",
    rowSound: "효과음",
    rowSoundDesc:
      "GitAnimals가 작업을 마치거나 입력을 요청할 때 알림음을 재생해요.",
    rowFlip: "좌우 반전",
    rowFlipDesc: "펫의 좌우를 뒤집어 반대 방향을 바라보게 해요.",
    rowOpenAtLogin: "로그인 시 실행",
    rowOpenAtLoginDesc: "로그인할 때 GitAnimals를 자동으로 시작해요.",
    rowStartWithClaude: "Claude Code와 함께 시작",
    rowStartWithClaudeDesc:
      "Claude Code 세션이 시작될 때마다 GitAnimals를 자동으로 실행해요.",
    rowAutoCheckUpdates: "자동으로 업데이트 확인",
    rowAutoCheckUpdatesDesc: "12시간마다 백그라운드에서 새 버전을 확인해요.",
    sectionUpdates: "업데이트",
    updateCurrentVersion: "현재 버전",
    updateLatestVersion: "최신 버전",
    updateLastChecked: "마지막 확인",
    updateNeverChecked: "아직 없음",
    updateStatusIdle: "업데이트를 확인할 준비가 됐어요.",
    updateStatusChecking: "GitHub에서 최신 릴리스를 확인하는 중이에요…",
    updateStatusAvailable: "더 새로운 버전이 있어요.",
    updateStatusDownloading: "업데이트를 다운로드하는 중이에요…",
    updateStatusReady: "업데이트가 다운로드되었고 설치할 준비가 됐어요.",
    updateStatusError: "마지막 업데이트 시도가 실패했어요.",
    updateStatusUpToDate: "현재 최신 버전을 사용 중이에요.",
    updateCheckNow: "지금 확인",
    updateDownloadNow: "업데이트 다운로드",
    updateInstallNow: "업데이트 적용",
    updateRestartNow: "재시작 후 업데이트",
    updateFlowGit: "개발 체크아웃",
    updateFlowAuto: "패키징 앱",
    rowBubbleFollow: "버블이 펫을 따라오기",
    rowBubbleFollowDesc:
      "권한 버블과 업데이트 버블을 화면 구석 대신 펫 옆에 표시해요.",
    rowHideBubbles: "모든 버블 숨기기",
    rowHideBubblesDesc: "권한·알림·업데이트 버블을 모두 숨겨요.",
    rowShowSessionId: "세션 ID 표시",
    rowShowSessionIdDesc: "버블 헤더와 세션 메뉴에 짧은 세션 ID를 추가해요.",
    sectionMacOS: "macOS",
    rowShowInMenuBar: "메뉴 막대에 표시",
    rowShowInMenuBarDesc: "macOS 메뉴 막대에 GitAnimals 아이콘을 표시해요.",
    rowShowInDock: "Dock에 표시",
    rowShowInDockDesc:
      "macOS Dock에 GitAnimals를 표시해요. 메뉴 막대와 Dock 중 하나는 반드시 켜져 있어야 해요.",
    sectionPrivacy: "개인정보",
    rowSendDiagnostics: "익명 진단 데이터 전송",
    rowSendDiagnosticsDesc:
      "크래시 리포트와 익명화된 이벤트 기록을 공유해 주시면, 펫이 사라지는 등의 문제를 진단하는 데 도움이 돼요. 개인정보는 포함되지 않아요.",
    placeholderTitle: "곧 제공됩니다",
    placeholderDesc:
      "이 패널은 향후 GitAnimals 버전에 추가될 예정이에요. 기획은 docs/plan-settings-panel.md에 있어요.",
    toastSaveFailed: "저장하지 못했어요: ",
    langEnglish: "English",
    langChinese: "中文",
    langKorean: "한국어",
    themeTabTitle: "테마",
    themeTabSubtitle:
      "고정된 테마가 우클릭 페르소나 서브메뉴에 표시돼요. 하나 이상은 반드시 고정되어 있어야 해요.",
    themeRefresh: "새로고침",
    themeRefreshing: "새로고침 중…",
    themeRefreshDone: "테마를 새로고침했어요.",
    themeRefreshFailed: "새로고침 실패: ",
    toastActiveLocked: "현재 활성 테마는 고정 해제할 수 없어요.",
    toastMinOneRequired: "하나 이상의 테마는 반드시 고정되어 있어야 해요.",
    toastPersonaRequired: "GitAnimals에서 이 펫을 획득하세요!",
    toastPersonaLink: "https://gitanimals.org",
    personaInfo: "잠긴 테마는 GitAnimals 펫이 필요해요.",
    personaInfoLink: "gitanimals.org에서 획득하기",
    userCardSignedIn: "로그인됨",
    userCardLoading: "계정 정보 불러오는 중…",
    userCardSignOut: "로그아웃",
    userCardSignInAgain: "다시 로그인",
    sessionExpiredToast: "세션이 만료되었습니다 — 다시 로그인해 주세요.",
  },
};

export const SIDEBAR_TABS = [
  {
    id: "general",
    icon: "\u2699",
    labelKey: "sidebarGeneral",
    available: true,
  },
  { id: "agents", icon: "\u26A1", labelKey: "sidebarAgents", available: true },
  { id: "theme", icon: "\u{1F3A8}", labelKey: "sidebarTheme", available: true },
  { id: "about", icon: "\u2139", labelKey: "sidebarAbout", available: true },
];

export const ABOUT_LINKS = {
  repository: "https://github.com/git-goods/gitanimals-on-desk",
  homepage: "https://gitanimals.org",
};

export function translate(snapshot, key) {
  const lang = (snapshot && snapshot.lang) || "en";
  const dict = STRINGS[lang] || STRINGS.en;
  return dict[key] || key;
}
